# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-07-18 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ML_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=60)),
                ('accuracy', models.CharField(max_length=60)),
                ('log_console_print', models.TextField(max_length=2048)),
            ],
        ),
    ]
